name = "HIDAPI"
uuid = "32bda012-3723-419b-9d2b-681d390a8526"
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
hidapi_jll = "fc16ec7e-3cba-5ca4-a17a-1acd8165bbee"

[compat]
CEnum = "0.4, 0.5"
Libdl = "1.11.0"
hidapi_jll = "0.15.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
