[general]
library_name = "libhidapi"
output_file_path = "../src/generated/libhidapi.jl"
use_julia_native_enum_type = false
print_using_CEnum = true
use_deterministic_symbol = true
is_local_header_only = true
smart_de_anonymize = true
extract_c_comment_style = "doxygen"

[codegen]
use_ccall_macro = true
use_julia_bool = true
always_NUL_terminated_string = true
opaque_func_arg_as_PtrCvoid = false
opaque_as_mutable_struct = false
is_function_strictly_typed = false

[codegen.macro]
macro_mode = "basic"
add_comment_for_skipped_macro = true
ignore_header_guards = true
ignore_pure_definition = true
